# Generated by Django 5.2.13 on 2026-05-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('specialization', models.CharField(max_length=20)),
                ('experience', models.IntegerField()),
                ('hospital', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=20)),
                ('emial', models.EmailField(max_length=254)),
            ],
        ),
    ]
