# Generated by Django 5.2.13 on 2026-05-14 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='emial',
            new_name='email',
        ),
    ]
